INSERT INTO public.badges (id, name, description, icon, color, audience) VALUES
  ('excellence',         'شارة التميز',           'تميز ملحوظ في الأداء',         '🌟', 'amber',   'student'),
  ('distinction',        'شارة التفوق',           'تفوق دراسي مستمر',             '🏆', 'amber',   'student'),
  ('participation',      'شارة المشاركة',         'مشاركة فعالة في الأنشطة',       '🙋', 'cyan',    'student'),
  ('creativity',         'شارة الإبداع',          'فكر إبداعي ومبتكر',            '🎨', 'rose',    'student'),
  ('creative',           'شارة المبدع',           'إبداع في معرض الإبداعات',       '✨', 'rose',    'student'),
  ('perseverance',       'شارة المثابرة',         'مثابرة وعدم استسلام',           '💪', 'emerald', 'student'),
  ('leadership',         'شارة القيادة',          'مهارات قيادية مميزة',           '👑', 'violet',  'student'),
  ('honor_student',      'طالب الأسبوع',          'الطالب الأعلى نقاطاً هذا الأسبوع','🎖️','amber',   'student'),
  ('helpful',            'شارة المساعد',          'مساعدة الزملاء',                '🤝', 'cyan',    'student'),
  ('first_activity',     'أول نشاط',              'أول نشاط مقبول',                '✨', 'emerald', 'student'),
  ('five_activities',    '٥ أنشطة',              'إنجاز 5 أنشطة',                 '🔥', 'rose',    'student'),
  ('ten_activities',     '١٠ أنشطة',             'إنجاز 10 أنشطة',                '⚡', 'violet',  'student'),
  ('competition_winner', 'بطل المسابقات',         'إجابة صحيحة في المسابقات',       '🥇', 'amber',   'student'),
  ('first_comment',      'أول تعليق',             'أول تعليق على نشاط',            '💬', 'cyan',    'student'),
  ('quiz_starter',       'بداية الاختبارات',      'حل أول اختبار',                 '📝', 'emerald', 'student'),
  ('quiz_master',        'سيد الاختبارات',        'حل 5 اختبارات أو أكثر',         '🧠', 'violet',  'student'),
  ('certificate_holder', 'حامل الشهادة',          'حصلت على شهادة تقدير',          '📜', 'amber',   'student'),
  ('top_teacher',        'المعلم المتميز',        'المعلم الأعلى نقاطاً هذا الأسبوع','🎓','emerald', 'teacher'),
  ('first_assignment',   'أول واجب',              'إنشاء أول واجب',                '📋', 'cyan',    'teacher'),
  ('first_quiz_made',    'أول اختبار',            'إنشاء أول اختبار',              '🧩', 'rose',    'teacher'),
  ('first_competition',  'أول مسابقة',            'إنشاء أول مسابقة',              '🏁', 'amber',   'teacher'),
  ('certificate_giver',  'مانح الشهادات',         'منح شهادة لطالب',               '🏅', 'violet',  'teacher')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  audience = EXCLUDED.audience;